CC=g++
PRE=$(CC) -c 
POST= -I/home/Shadow/lisana/cpp -I/usr/local/include -L/usr/local/lib/ -lprotobuf
all: 
		${PRE} Account.pb.cc -o Account.pb.o ${POST}
		${PRE} AttributeSerializer.pb.cc -o AttributeSerializer.pb.o ${POST}
		${PRE} GameMessage.pb.cc -o GameMessage.pb.o ${POST}
		${PRE} GBHandle.pb.cc -o GBHandle.pb.o ${POST}
		${PRE} google/protobuf/descriptor.pb.cc -o google/protobuf/descriptor.pb.o ${POST}
		${PRE} Hero.pb.cc -o Hero.pb.o ${POST}
		${PRE} Hireling.pb.cc -o Hireling.pb.o ${POST}
		${PRE} ItemCrafting.pb.cc -o ItemCrafting.pb.o ${POST}
		${PRE} Items.pb.cc -o Items.pb.o ${POST}
		${PRE} lib/config/process_config.pb.cc -o lib/config/process_config.pb.o ${POST}
		${PRE} lib/profanity/profanity.pb.cc -o lib/profanity/profanity.pb.o ${POST}
		${PRE} lib/protocol/attribute.pb.cc -o lib/protocol/attribute.pb.o ${POST}
		${PRE} lib/protocol/content_handle.pb.cc -o lib/protocol/content_handle.pb.o ${POST}
		${PRE} lib/protocol/descriptor.pb.cc -o lib/protocol/descriptor.pb.o ${POST}
		${PRE} lib/protocol/entity.pb.cc -o lib/protocol/entity.pb.o ${POST}
		${PRE} lib/protocol/exchange.pb.cc -o lib/protocol/exchange.pb.o ${POST}
		${PRE} lib/protocol/exchange_object_provider.pb.cc -o lib/protocol/exchange_object_provider.pb.o ${POST}
		${PRE} lib/protocol/invitation.pb.cc -o lib/protocol/invitation.pb.o ${POST}
		${PRE} lib/protocol/resource.pb.cc -o lib/protocol/resource.pb.o ${POST}
		${PRE} lib/rpc/connection.pb.cc -o lib/rpc/connection.pb.o ${POST}
		${PRE} lib/rpc/rpc.pb.cc -o lib/rpc/rpc.pb.o ${POST}
		${PRE} OnlineService.pb.cc -o OnlineService.pb.o ${POST}
		${PRE} PartyMessage.pb.cc -o PartyMessage.pb.o ${POST}
		${PRE} Quest.pb.cc -o Quest.pb.o ${POST}
		${PRE} service/authentication/authentication.pb.cc -o service/authentication/authentication.pb.o ${POST}
		${PRE} service/channel/channel_types.pb.cc -o service/channel/channel_types.pb.o ${POST}
		${PRE} service/channel/definition/channel.pb.cc -o service/channel/definition/channel.pb.o ${POST}
		${PRE} service/channel_invitation/channel_invitation_types.pb.cc -o service/channel_invitation/channel_invitation_types.pb.o ${POST}
		${PRE} service/channel_invitation/definition/channel_invitation.pb.cc -o service/channel_invitation/definition/channel_invitation.pb.o ${POST}
		${PRE} service/chat/definition/chat.pb.cc -o service/chat/definition/chat.pb.o ${POST}
		${PRE} service/chat/definition/chat_types.pb.cc -o service/chat/definition/chat_types.pb.o ${POST}
		${PRE} service/exchange/exchange_types.pb.cc -o service/exchange/exchange_types.pb.o ${POST}
		${PRE} service/followers/definition/followers.pb.cc -o service/followers/definition/followers.pb.o ${POST}
		${PRE} service/friends/definition/friends.pb.cc -o service/friends/definition/friends.pb.o ${POST}
		${PRE} service/friends/friends_types.pb.cc -o service/friends/friends_types.pb.o ${POST}
		${PRE} service/game_master/game_factory.pb.cc -o service/game_master/game_factory.pb.o ${POST}
		${PRE} service/game_master/game_master.pb.cc -o service/game_master/game_master.pb.o ${POST}
		${PRE} service/game_master/game_master_types.pb.cc -o service/game_master/game_master_types.pb.o ${POST}
		${PRE} service/game_utilities/game_utilities.pb.cc -o service/game_utilities/game_utilities.pb.o ${POST}
		${PRE} service/notification/notification.pb.cc -o service/notification/notification.pb.o ${POST}
		${PRE} service/party/definition/party.pb.cc -o service/party/definition/party.pb.o ${POST}
		${PRE} service/presence/presence.pb.cc -o service/presence/presence.pb.o ${POST}
		${PRE} service/presence/presence_types.pb.cc -o service/presence/presence_types.pb.o ${POST}
		${PRE} service/search/search.pb.cc -o service/search/search.pb.o ${POST}
		${PRE} service/search/search_types.pb.cc -o service/search/search_types.pb.o ${POST}
		${PRE} service/server_pool/server_pool.pb.cc -o service/server_pool/server_pool.pb.o ${POST}
		${PRE} service/storage/storage.pb.cc -o service/storage/storage.pb.o ${POST}
		${PRE} service/toon/toon.pb.cc -o service/toon/toon.pb.o ${POST}
		${PRE} service/toon/toon_external.pb.cc -o service/toon/toon_external.pb.o ${POST}
		${PRE} service/user_manager/user_manager.pb.cc -o service/user_manager/user_manager.pb.o ${POST}
		${PRE} Settings.pb.cc -o Settings.pb.o ${POST}
		${PRE} Stats.pb.cc -o Stats.pb.o ${POST}




