/*
    This file is part of Lisana.

    Lisana is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Lisana is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Lisana.  If not, see <http://www.gnu.org/licenses/>.
*/

// FriendsNotify
// bnet.protocol.friends.FriendsNotify
//
// { NotifyFriendAdded .bnet.protocol.friends.FriendNotification .bnet.protocol.NO_RESPONSE }
// { NotifyFriendRemoved .bnet.protocol.friends.FriendNotification .bnet.protocol.NO_RESPONSE }
// { NotifyReceivedInvitationAdded .bnet.protocol.friends.InvitationAddedNotification .bnet.protocol.NO_RESPONSE }
// { NotifyReceivedInvitationRemoved .bnet.protocol.friends.InvitationRemovedNotification .bnet.protocol.NO_RESPONSE }
// { NotifySentInvitationRemoved .bnet.protocol.friends.InvitationRemovedNotification .bnet.protocol.NO_RESPONSE }


#include "FriendsNotify.h"

#include <iostream>

using namespace google::protobuf;


CServiceFriendsNotify::CServiceFriendsNotify()
{
	// place here any initialization (?)
}

CServiceFriendsNotify::CServiceFriendsNotify(CServiceMgr* owner=0,int SID=0, int sHash=0, std::string serviceName="") : CService(owner,SID, sHash, serviceName)
{
	//what goes here now?
}

Message* CServiceFriendsNotify::GetMethodMessage(int MethodID, bool request) {
	switch (MethodID) {
		case 1:
			if (request) { return ::bnet::protocol::friends::FriendNotification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }
		case 2:
			if (request) { return ::bnet::protocol::friends::FriendNotification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }
		case 3:
			if (request) { return ::bnet::protocol::friends::InvitationAddedNotification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }
		case 4:
			if (request) { return ::bnet::protocol::friends::InvitationRemovedNotification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }
		case 5:
			if (request) { return ::bnet::protocol::friends::InvitationRemovedNotification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return NULL;
	}
}

//This function was autogenerated:
bool CServiceFriendsNotify::DispatchMethod(int MethodID, bool request, TCPSocket *sock, apacket* packet) {
	switch (MethodID) {
		case 1:
			if (request) { return handle_NotifyFriendAdded_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }
		case 2:
			if (request) { return handle_NotifyFriendRemoved_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }
		case 3:
			if (request) { return handle_NotifyReceivedInvitationAdded_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }
		case 4:
			if (request) { return handle_NotifyReceivedInvitationRemoved_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }
		case 5:
			if (request) { return handle_NotifySentInvitationRemoved_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return false;
	}
}

bool CServiceFriendsNotify::handle_NotifyFriendAdded_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::friends::FriendNotification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}


bool CServiceFriendsNotify::handle_NotifyFriendRemoved_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::friends::FriendNotification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}


bool CServiceFriendsNotify::handle_NotifyReceivedInvitationAdded_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::friends::InvitationAddedNotification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}


bool CServiceFriendsNotify::handle_NotifyReceivedInvitationRemoved_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::friends::InvitationRemovedNotification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}


bool CServiceFriendsNotify::handle_NotifySentInvitationRemoved_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::friends::InvitationRemovedNotification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}



CServiceFriendsNotify::~CServiceFriendsNotify(void)
{
	std::cout << "Bye from authserv.";
}

