/*
    This file is part of Lisana.

    Lisana is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Lisana is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Lisana.  If not, see <http://www.gnu.org/licenses/>.
*/

// NotificationListener
// bnet.protocol.notification.NotificationListener
//
// { OnNotificationReceived .bnet.protocol.notification.Notification .bnet.protocol.NO_RESPONSE }


#include "NotificationListener.h"

#include <iostream>

using namespace google::protobuf;


CServiceNotificationListener::CServiceNotificationListener()
{
	// place here any initialization (?)
}

CServiceNotificationListener::CServiceNotificationListener(CServiceMgr* owner=0,int SID=0, int sHash=0, std::string serviceName="") : CService(owner,SID, sHash, serviceName)
{
	//what goes here now?
}

Message* CServiceNotificationListener::GetMethodMessage(int MethodID, bool request) {
	switch (MethodID) {
		case 1:
			if (request) { return ::bnet::protocol::notification::Notification::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return NULL;
	}
}

//This function was autogenerated:
bool CServiceNotificationListener::DispatchMethod(int MethodID, bool request, TCPSocket *sock, apacket* packet) {
	switch (MethodID) {
		case 1:
			if (request) { return handle_OnNotificationReceived_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return false;
	}
}

bool CServiceNotificationListener::handle_OnNotificationReceived_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::notification::Notification* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}



CServiceNotificationListener::~CServiceNotificationListener(void)
{
	std::cout << "Bye from authserv.";
}

