/*
    This file is part of Lisana.

    Lisana is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Lisana is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Lisana.  If not, see <http://www.gnu.org/licenses/>.
*/

// SearchService
// bnet.protocol.search.SearchService
//
// { FindMatches .bnet.protocol.search.FindMatchesRequest .bnet.protocol.search.FindMatchesResponse }
// { SetObject .bnet.protocol.search.SetObjectRequest .bnet.protocol.NO_RESPONSE }
// { RemoveObjects .bnet.protocol.search.RemoveObjectsRequest .bnet.protocol.NO_RESPONSE }


#include "SearchService.h"

#include <iostream>

using namespace google::protobuf;


CServiceSearchService::CServiceSearchService()
{
	// place here any initialization (?)
}

CServiceSearchService::CServiceSearchService(CServiceMgr* owner=0,int SID=0, std::string serviceName=string(SERVICE_SearchService_NAME)) : 
	CService(owner, SID, serviceName)
{
	//what goes here now?
}


Message* CServiceSearchService::GetMethodMessage(int MethodID, bool request) {
	switch (MethodID) {
		case 1:
			if (request) { return ::bnet::protocol::search::FindMatchesRequest::default_instance().New(); }
			else { return ::bnet::protocol::search::FindMatchesResponse::default_instance().New(); }
		case 2:
			if (request) { return ::bnet::protocol::search::SetObjectRequest::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }
		case 3:
			if (request) { return ::bnet::protocol::search::RemoveObjectsRequest::default_instance().New(); }
			else { cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return NULL;
	}
}

//This function was autogenerated:
bool CServiceSearchService::DispatchMethod(int MethodID, bool request, TCPSocket *sock, apacket* packet) {
	switch (MethodID) {
		case 1:
			if (request) { return handle_FindMatches_Request(sock, packet); }
			else {	return handle_FindMatches_Response(sock, packet); }
		case 2:
			if (request) { return handle_SetObject_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }
		case 3:
			if (request) { return handle_RemoveObjects_Request(sock, packet); }
			else {cerr << "error: method has no response data" << endl; }

		default:
			cerr << "error: method not implemented" << endl;
			return false;
	}
}

bool CServiceSearchService::handle_FindMatches_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::search::FindMatchesRequest* request;
	::bnet::protocol::search::FindMatchesResponse response;
	request = (::bnet::protocol::search::FindMatchesRequest*) packet;
	
	// add some info to the packet? 

	sendheader(sock, 0xFE, 0, packet->hdr->reqid, 0, response.ByteSize());
	sendmsgdata(sock, &response);

	// do something...
	
	return true;
}

bool CServiceSearchService::handle_FindMatches_Response(TCPSocket *sock, apacket* packet)

{
	::bnet::protocol::search::FindMatchesResponse* response;
	response = (::bnet::protocol::search::FindMatchesResponse*) packet->msg;
	//do something...
	
	return true;
}

bool CServiceSearchService::handle_SetObject_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::search::SetObjectRequest* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}


bool CServiceSearchService::handle_RemoveObjects_Request(TCPSocket *sock, apacket* packet)
{
	::bnet::protocol::search::RemoveObjectsRequest* request;
		//this packet has no response asociated.
	// do something...
	
	return true;
}



CServiceSearchService::~CServiceSearchService(void)
{
	std::cout << "Bye from authserv.";
}

